### ISSUE TITLE
浏览器请求静态资源的并发数

### ISSUE THREAD

**Issue by tvrcgo** [tvrcgo/notes#4]
在浏览器上测试了一下请求 JS, CSS, IMG 的并发数，都是动态创建标签一次性写入 head 和 body。
测试条件：
- Chrome 43.x, Firefox 38.x
- 同一个域下的 JS, CSS, IMG

各个浏览器的并发数 http://www.stevesouders.com/blog/2008/03/20/roundup-on-parallel-connections/ 这里有列出。Chrome 和 Firefox 的并发数都是 6，但不同类型资源的加载方式还是有差别。
### JavaScript

JS 都是串行加载。

Chrome
![js](https://cloud.githubusercontent.com/assets/237062/7763680/3bc9d922-0077-11e5-9929-2dffef1be81a.png)

Firefox
![ff-js](https://cloud.githubusercontent.com/assets/237062/7763966/97e1e1c4-007b-11e5-8806-5a0d4292463f.png)
### CSS

Chrome 中所有 link 一开始会同时建立连接，但每次只并行加载 6 个资源，其余资源会被延迟加载。
![css](https://cloud.githubusercontent.com/assets/237062/7763688/506e296e-0077-11e5-9f47-4507a3ab760d.png)

Firefox 中相同。
![qq 20150522115935](https://cloud.githubusercontent.com/assets/237062/7763866/1887cca0-007a-11e5-8018-78780d937635.png)
### IMG

Chrome 中 IMG 每次只会建立 6 个连接并行，完成后再建立连接加载剩下的IMG。
![img](https://cloud.githubusercontent.com/assets/237062/7763690/5d19c0ce-0077-11e5-8c84-933c012a01f3.png)

Firefox 中所有 IMG 会同时建立连接，每次并行加载 6 个资源，其余延迟加载，和 Chrome 加载CSS的方式相同。
![qq 20150522120229](https://cloud.githubusercontent.com/assets/237062/7763911/b8e1d42a-007a-11e5-97c3-727cb52d3838.png)

**Comment by ghost** [comment]
http://coolshell.cn/articles/9749.html 这页面 加载js 前几个文件是串行，中间几个是并行，这样看来js是并行和串行？

**Comment by legend80s** [comment]
Chrome 浏览器通 hostname 默认最大并发度：http = 6，https > 13。Version 61.0.3163.100
我是用的 angular $q.all 并发 $http get 请求。请问你知道 https 最大并发度么？

**Comment by GerryIsWarrior** [comment]
有没有js代码去检测浏览器最大的并发量的检测代码

**Comment by tvrcgo** [comment]
@legend80s https 没测过

**Comment by tvrcgo** [comment]
@GerryIsWarrior  你用它的场景是 ？

**Comment by GerryIsWarrior** [comment]
检测每个浏览器的最大并发数，然后做一个请求池，复用请求，减少创建过程中的损耗

**Comment by tvrcgo** [comment]
@GerryIsWarrior  试试 http 2 吧
